// <auto-generated />
using System;
using EatMyMovies.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EatMyMovies.DataAccess.Migrations
{
    [DbContext(typeof(EatMyMoviesContext))]
    [Migration("20260611161507_DatabaseIntegrityAndModelCleanup")]
    partial class DatabaseIntegrityAndModelCleanup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EatMyMovies.DataAccess.Models.Genre", b =>
                {
                    b.Property<Guid>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GenreId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("EatMyMovies.DataAccess.Models.List", b =>
                {
                    b.Property<Guid>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ListId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Lists");
                });

            modelBuilder.Entity("EatMyMovies.DataAccess.Models.ListRanking", b =>
                {
                    b.Property<Guid>("ListRankingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.HasKey("ListRankingId");

                    b.HasIndex("MovieId");

                    b.HasIndex("ListId", "MovieId")
                        .IsUnique();

                    b.HasIndex("ListId", "Ranking")
                        .IsUnique();

                    b.ToTable("ListRankings", t =>
                        {
                            t.HasCheckConstraint("CK_ListRankings_Ranking_Positive", "[Ranking] > 0");
                        });
                });

            modelBuilder.Entity("EatMyMovies.DataAccess.Models.Movie", b =>
                {
                    b.Property<Guid>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.HasIndex("TmdbId")
                        .IsUnique()
                        .HasFilter("[TmdbId] IS NOT NULL");

                    b.ToTable("Movies", t =>
                        {
                            t.HasCheckConstraint("CK_Movies_TmdbId_Positive", "[TmdbId] IS NULL OR [TmdbId] > 0");
                        });
                });

            modelBuilder.Entity("EatMyMovies.DataAccess.Models.MovieGenre", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId", "MovieId");

                    b.ToTable("MovieGenres");
                });

            modelBuilder.Entity("EatMyMovies.DataAccess.Models.ListRanking", b =>
                {
                    b.HasOne("EatMyMovies.DataAccess.Models.List", "List")
                        .WithMany("ListRankings")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatMyMovies.DataAccess.Models.Movie", "Movie")
                        .WithMany("ListRankings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("EatMyMovies.DataAccess.Models.MovieGenre", b =>
                {
                    b.HasOne("EatMyMovies.DataAccess.Models.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatMyMovies.DataAccess.Models.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("EatMyMovies.DataAccess.Models.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("EatMyMovies.DataAccess.Models.List", b =>
                {
                    b.Navigation("ListRankings");
                });

            modelBuilder.Entity("EatMyMovies.DataAccess.Models.Movie", b =>
                {
                    b.Navigation("ListRankings");

                    b.Navigation("MovieGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
