// <auto-generated />
using System;
using EatMyMovies.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EatMyMovies.DataAccess.Migrations
{
    [DbContext(typeof(EatMyMoviesContext))]
    [Migration("20260611155556_AsyncRepositoryQueryIndexes")]
    partial class AsyncRepositoryQueryIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EatMyMovies.DataAccess.Models.Genre", b =>
                {
                    b.Property<Guid>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("EatMyMovies.DataAccess.Models.List", b =>
                {
                    b.Property<Guid>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ListId");

                    b.HasIndex("Name");

                    b.ToTable("Lists");
                });

            modelBuilder.Entity("EatMyMovies.DataAccess.Models.ListRanking", b =>
                {
                    b.Property<Guid>("ListRankingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.HasKey("ListRankingId");

                    b.HasIndex("MovieId");

                    b.HasIndex("ListId", "MovieId");

                    b.HasIndex("ListId", "Ranking");

                    b.ToTable("ListRankings");
                });

            modelBuilder.Entity("EatMyMovies.DataAccess.Models.Movie", b =>
                {
                    b.Property<Guid>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.HasIndex("Title");

                    b.HasIndex("TmdbId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("EatMyMovies.DataAccess.Models.MovieGenre", b =>
                {
                    b.Property<Guid>("MovieGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MovieGenreId");

                    b.HasIndex("MovieId");

                    b.HasIndex("GenreId", "MovieId");

                    b.ToTable("MovieGenres");
                });

            modelBuilder.Entity("EatMyMovies.DataAccess.Models.ListRanking", b =>
                {
                    b.HasOne("EatMyMovies.DataAccess.Models.List", "List")
                        .WithMany()
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatMyMovies.DataAccess.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("EatMyMovies.DataAccess.Models.MovieGenre", b =>
                {
                    b.HasOne("EatMyMovies.DataAccess.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatMyMovies.DataAccess.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
